image: node:22

stages:
  - build
  # - deploy

cache:
  paths:
    - node_modules/

variables:
  NODE_ENV: production
  APP_ID: d308mi317guky4
  BRANCH_NAME: main
  ALLOWED_DOMAINS: https://elcomercio.pe
  PIANO_API: https://api.piano.io
  ELCOMERCIO_AID: Enoqbpnkpu
  GESTION_AID: UmAkgzZ4pu
  CLUBELCOMERCIO_AID: fiiSp96Gpu
  JWT_SECRET: pablitoestuvoaqui
  SENTRY_DNS: https://5f89e34be9c14841a3dea359c77c1376@sentry.ec.pe/143
  S3_BUCKET: sso-piano-bucket-pablito-pe

before_script:
  - apt-get update -y && apt-get install -y unzip curl # para instalar AWS CLI
  - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
  - unzip awscliv2.zip
  - ./aws/install
  - aws --version
  # Configura credenciales (asegúrate de setearlas como variables CI/CD en GitLab)
  - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
  - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
  - aws configure set default.region $AWS_DEFAULT_REGION

# ========================================
# JOB: BUILD
# ========================================
build:
  stage: build
  script:
    - rm -rf node_modules .next
    - apt-get update -y
    - apt-get install -y zip
    - npm ci

    - PIANO_API=$PIANO_API ALLOWED_DOMAINS=$ALLOWED_DOMAINS JWT_SECRET=$JWT_SECRET ELCOMERCIO_AID=$ELCOMERCIO_AID GESTION_AID=$GESTION_AID CLUBELCOMERCIO_AID=$CLUBELCOMERCIO_AID ELCOMERCIO_API_TOKEN=$ELCOMERCIO_API_TOKEN GESTION_API_TOKEN=$GESTION_API_TOKEN CLUBELCOMERCIO_API_TOKEN=$CLUBELCOMERCIO_API_TOKEN SENTRY_DNS=$SENTRY_DNS npm run build

    - zip -r build.zip .next package.json next.config.ts public

    - aws s3 cp build.zip s3://$S3_BUCKET/build.zip

    - aws amplify start-deployment --app-id $APP_ID --branch-name main --source-url s3://$S3_BUCKET/build.zip --source-url-type ZIP

  artifacts:
    paths:
      - build.zip
  only:
    - main

# ========================================
# JOB: DEPLOY
# ========================================
# deploy:
#   stage: deploy
#   dependencies:
#     - build
#   script:
#     # Actualizamos variables de entorno en Amplify
#     # - aws amplify update-app --app-id $APP_ID --environment-variables ALLOWED_DOMAINS=$ALLOWED_DOMAIN,PIANO_API=$PIANO_API,ELCOMERCIO_AID=$ELCOMERCIO_AID,GESTION_AID=$GESTION_AID,CLUBELCOMERCIO_AID=$CLUBELCOMERCIO_AID,ELCOMERCIO_API_TOKEN=$ELCOMERCIO_API_TOKEN,GESTION_API_TOKEN=$GESTION_API_TOKEN,CLUBELCOMERCIO_API_TOKEN=$CLUBELCOMERCIO_API_TOKEN,JWT_SECRET=$JWT_SECRET,SENTRY_DNS=$SENTRY_DNS

#     # Lanzamos el deployment
#     - DEPLOYMENT_ID=$(aws amplify create-deployment --app-id $APP_ID --branch-name main --zip-file fileb://build.zip --query "deploymentId" --output text)

#     - aws amplify start-deployment --app-id $APP_ID --branch-name main --deployment-id $DEPLOYMENT_ID
#   only:
#     - main
